# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('activity_description', models.CharField(max_length=255, verbose_name='Descripci\xf3n')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
    ]
