# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Descripci\xf3n'),
        ),
    ]
