# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-16 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0002_auto_20160817_1828'),
        ('projects', '0005_project_project_client'),
        ('suppliers', '0003_auto_20160818_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField(verbose_name='Fecha')),
                ('expense_description', models.CharField(max_length=255, verbose_name='Descripci\xf3n')),
                ('expense_document', models.CharField(max_length=255, verbose_name='Documento')),
                ('expense_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Subtotal')),
                ('expense_iv', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='IV Total')),
                ('expense_total', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Precio Total')),
                ('expense_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Activity', verbose_name='Actividad')),
                ('expense_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Proyecto')),
                ('expense_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.Supplier', verbose_name='Proveedor')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
            },
        ),
    ]
