# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-17 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='expense_iv',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='expense_subtotal',
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_bill_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Factura'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_description',
            field=models.CharField(max_length=255, verbose_name='Detalle'),
        ),
    ]
