# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_activity',
            field=models.ManyToManyField(blank=True, to='activities.Activity', verbose_name='Actividades'),
        ),
    ]
