# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-12 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0003_auto_20161012_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='pay_document_num',
            field=models.CharField(max_length=100, null=True, verbose_name='Comprobante N\xfamero'),
        ),
    ]
