# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-15 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0004_auto_20161012_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='pay_interest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Total de intereses'),
        ),
    ]
