# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-15 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0005_pay_pay_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='pay_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Total del Dep\xf3sito'),
        ),
        migrations.AddField(
            model_name='paydetail',
            name='pay_detail_interest',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True, verbose_name='Inter\xe9s'),
        ),
    ]
