# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplier_email2',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email Contabilidad'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_email3',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email Administraci\xf3n'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_phone2',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, verbose_name='Tel\xe9fono Contabilidad'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_phone3',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, verbose_name='Tel\xe9fono Administraci\xf3n'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Direcci\xf3n'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email Ventas'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_phone',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, verbose_name='Tel\xe9fono Ventas'),
        ),
    ]
