# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_auto_20160817_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Ventas'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_email2',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Contabilidad'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_email3',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Administraci\xf3n'),
        ),
    ]
