# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_product_list',
            field=models.ManyToManyField(to='orders.OrderDetail', verbose_name='Lista de Detalles'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order_detail_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Total'),
        ),
    ]
