# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='order_detail_product_code',
            field=models.CharField(default='', max_length=255, verbose_name='C\xf3digo'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order_detail_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Id Producto'),
        ),
    ]
