# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20160731_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Precio Total'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order_detail_price',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Precio unitario'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order_detail_total',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Precio Total'),
        ),
    ]
