# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20160811_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_iv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='IV Total'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order_detail_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Descuento %'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order_detail_iv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='IV %'),
        ),
    ]
