# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20160813_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Subtotal'),
        ),
    ]
