# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20160731_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='order_detail_description',
            field=models.CharField(default='', max_length=255, verbose_name='Descripci\xf3n'),
        ),
    ]
