# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_order_deliver_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='order_detail_product',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Id Producto'),
        ),
    ]
