# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_auto_20160907_1521'),
        ('orders', '0006_auto_20160907_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requests.Request', verbose_name='Pedido'),
        ),
    ]
