# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_id',
            field=models.PositiveIntegerField(default=0, verbose_name='Identificaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_address',
            field=models.CharField(default='', max_length=255, verbose_name='Direcci\xf3n'),
        ),
    ]
