# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20160807_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Direcci\xf3n'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, verbose_name='Identificaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_phone',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=11, verbose_name='N\xfamero de Tel\xe9fono'),
        ),
    ]
