# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20160807_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_address',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Direcci\xf3n'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True, verbose_name='Identificaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_phone',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True, verbose_name='N\xfamero de Tel\xe9fono'),
        ),
    ]
