# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento %'),
        ),
    ]
