# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_avg_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio promedio \u20a1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_min_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio m\xednimo \u20a1'),
        ),
    ]
