# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20160709_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio \u20a1'),
        ),
    ]
