# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 00:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_product_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdepartment',
            options={'ordering': ['id'], 'verbose_name': 'Familia', 'verbose_name_plural': 'Familias'},
        ),
    ]
