# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True, verbose_name='C\xf3digo'),
        ),
    ]
