# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20160730_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productdepartment_name', models.CharField(max_length=255, unique=True, verbose_name='Nombre del Departamento')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_avg_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_min_price',
        ),
        migrations.AddField(
            model_name='product',
            name='product_taxes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Impuestos %'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_unit',
            field=models.CharField(default='', max_length=255, verbose_name='Unidad'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_usetaxes',
            field=models.BooleanField(default=False, verbose_name='Usa Impuestos?'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_department',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductDepartment', verbose_name='Departamento'),
        ),
    ]
