# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20160809_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdepartment',
            name='productdepartment_code',
            field=models.CharField(max_length=2, unique=True, verbose_name='Identificador de Familia'),
        ),
        migrations.AlterField(
            model_name='productsubdepartment',
            name='productsubdepartment_code',
            field=models.CharField(max_length=2, verbose_name='Identificador de Sub-Familia'),
        ),
    ]
