# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20160809_0730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsubdepartment',
            options={'ordering': ['id'], 'verbose_name': 'Sub-Familia', 'verbose_name_plural': 'Sub-Familias'},
        ),
        migrations.AlterField(
            model_name='product',
            name='product_unit',
            field=models.CharField(default='Unidad', max_length=255, verbose_name='Unidad'),
        ),
    ]
