# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20160809_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdepartment',
            name='productdepartment_consecutive',
        ),
        migrations.RemoveField(
            model_name='productsubdepartment',
            name='productsubdepartment_consecutive',
        ),
        migrations.AddField(
            model_name='product',
            name='product_consecutive',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='Consecutivo'),
        ),
    ]
