# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_date', models.DateField(verbose_name='Fecha')),
                ('bill_total', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Precio Total')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='BillDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_detail_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('bill_detail_amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Cantidad')),
                ('bill_detail_total', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Precio Total')),
                ('bill_detail_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Producto')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Detalle de la factura',
                'verbose_name_plural': 'Detalles de facturas',
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_detail_list',
            field=models.ManyToManyField(to='bills.BillDetail', verbose_name='Lista de detalles'),
        ),
    ]
