# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='bill_product_list',
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_detail_list',
            field=models.ManyToManyField(to='bills.BillDetail', verbose_name='Lista de detalles'),
        ),
    ]
