# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bills', '0001_initial'),
        ('orders', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.Order', verbose_name='Orden de compra'),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.Supplier', verbose_name='Proveedor'),
        ),
    ]
