# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_auto_20160811_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_iv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='IV Total'),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='billdetail',
            name='bill_detail_description',
            field=models.CharField(default='', max_length=255, verbose_name='Descripci\xf3n'),
        ),
        migrations.AddField(
            model_name='billdetail',
            name='bill_detail_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Descuento %'),
        ),
        migrations.AddField(
            model_name='billdetail',
            name='bill_detail_iv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='IV %'),
        ),
        migrations.AddField(
            model_name='billdetail',
            name='bill_detail_product_code',
            field=models.CharField(default='', max_length=255, verbose_name='C\xf3digo'),
        ),
        migrations.AddField(
            model_name='billdetail',
            name='bill_detail_unit',
            field=models.CharField(default='', max_length=255, verbose_name='Unidad'),
        ),
    ]
