# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20160731_1139'),
        ('bills', '0002_auto_20160802_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.Order', verbose_name='Orden de compra'),
        ),
    ]
