# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_auto_20160814_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billdetail',
            name='bill_detail_price',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Precio unitario'),
        ),
        migrations.AlterField(
            model_name='billdetail',
            name='bill_detail_total',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Precio Total'),
        ),
    ]
