# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_auto_20160815_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_total',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Precio Total'),
        ),
    ]
