# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_auto_20160815_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_supplier_bill',
            field=models.CharField(blank=True, default='0', max_length=255, verbose_name='# Factura Proveedor'),
        ),
    ]
