# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_bill_bill_supplier_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billdetail',
            name='bill_detail_product',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Producto'),
        ),
    ]
