# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_auto_20160907_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_payed',
            field=models.BooleanField(default=False, verbose_name='Pagada?'),
        ),
    ]
