# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0008_bill_bill_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_debt',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True, verbose_name='Saldo de Factura'),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_half_payed',
            field=models.BooleanField(default=False, verbose_name='Con Abono?'),
        ),
    ]
