# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-12 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0009_auto_20160922_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_debt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Saldo de Factura'),
        ),
    ]
